name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Debug APK
      run: ./gradlew --no-daemon assembleDebug
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
        if-no-files-found: error
