name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: shady-debug-apk
        path: app/build/outputs/apk/debug/*.apk
